services:
  backend:
    container_name: backend
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MYSQL_PASSWORD: 'password123'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'ransa'
      SECRET_KEY: 'MAXIMUM_SECRET_ALLOWED_BY_USER'
      MYSQL_HOST: 'mysql_dock'
      MYSQL_PORT: 3306
    volumes:
      - .:/app
    command: npm start
  db:
    container_name: mysql_dock
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_DATABASE: 'ransa'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
